main: aliuly\grabbag\Main
api: [3.0.0]
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 2.4.4
author: aliuly
website: https://github.com/Muirfield/GrabBag
softdepend: FastTransfer
